# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab1 = QtWidgets.QWidget()
        self.tab1.setObjectName("tab1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab1)
        self.verticalLayout_2.setContentsMargins(0, 2, 0, 0)
        self.verticalLayout_2.setSpacing(1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(5, 0, -1, 0)
        self.horizontalLayout.setSpacing(5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.tab1)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.m_search_edit = QtWidgets.QLineEdit(self.tab1)
        self.m_search_edit.setObjectName("m_search_edit")
        self.horizontalLayout.addWidget(self.m_search_edit)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.m_table = QtWidgets.QTableWidget(self.tab1)
        self.m_table.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.m_table.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.m_table.setObjectName("m_table")
        self.m_table.setColumnCount(0)
        self.m_table.setRowCount(0)
        self.verticalLayout_2.addWidget(self.m_table)
        self.tabWidget.addTab(self.tab1, "")
        self.tab2 = QtWidgets.QWidget()
        self.tab2.setObjectName("tab2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.tab2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.m_map_table = QtWidgets.QTableWidget(self.tab2)
        self.m_map_table.setStyleSheet("")
        self.m_map_table.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.m_map_table.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.m_map_table.setObjectName("m_map_table")
        self.m_map_table.setColumnCount(0)
        self.m_map_table.setRowCount(0)
        self.horizontalLayout_2.addWidget(self.m_map_table)
        self.tabWidget.addTab(self.tab2, "")
        self.tab3 = QtWidgets.QWidget()
        self.tab3.setObjectName("tab3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.m_lang_cnf_tab = QtWidgets.QTableWidget(self.tab3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.m_lang_cnf_tab.sizePolicy().hasHeightForWidth())
        self.m_lang_cnf_tab.setSizePolicy(sizePolicy)
        self.m_lang_cnf_tab.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.m_lang_cnf_tab.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.m_lang_cnf_tab.setObjectName("m_lang_cnf_tab")
        self.m_lang_cnf_tab.setColumnCount(0)
        self.m_lang_cnf_tab.setRowCount(0)
        self.verticalLayout_3.addWidget(self.m_lang_cnf_tab)
        self.line = QtWidgets.QFrame(self.tab3)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_3.addWidget(self.line)
        self.m_lang_tab = QtWidgets.QTableWidget(self.tab3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(3)
        sizePolicy.setHeightForWidth(self.m_lang_tab.sizePolicy().hasHeightForWidth())
        self.m_lang_tab.setSizePolicy(sizePolicy)
        self.m_lang_tab.setMaximumSize(QtCore.QSize(16777215, 150))
        self.m_lang_tab.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.m_lang_tab.setObjectName("m_lang_tab")
        self.m_lang_tab.setColumnCount(0)
        self.m_lang_tab.setRowCount(0)
        self.verticalLayout_3.addWidget(self.m_lang_tab)
        self.tabWidget.addTab(self.tab3, "")
        self.verticalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 23))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.m_statusbar = QtWidgets.QStatusBar(MainWindow)
        self.m_statusbar.setSizeGripEnabled(True)
        self.m_statusbar.setObjectName("m_statusbar")
        MainWindow.setStatusBar(self.m_statusbar)
        self.menu_export_all = QtWidgets.QAction(MainWindow)
        self.menu_export_all.setObjectName("menu_export_all")
        self.menu_export_all_map = QtWidgets.QAction(MainWindow)
        self.menu_export_all_map.setObjectName("menu_export_all_map")
        self.menu_export_all_c_map = QtWidgets.QAction(MainWindow)
        self.menu_export_all_c_map.setObjectName("menu_export_all_c_map")
        self.menu.addAction(self.menu_export_all)
        self.menu.addAction(self.menu_export_all_map)
        self.menu.addAction(self.menu_export_all_c_map)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "配置导出工具"))
        self.label.setText(_translate("MainWindow", "搜索："))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab1), _translate("MainWindow", "功能配置"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab2), _translate("MainWindow", "地图配置"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab3), _translate("MainWindow", "多语言翻译配置"))
        self.menu.setTitle(_translate("MainWindow", "工具"))
        self.menu_export_all.setText(_translate("MainWindow", "导出所有功能配置"))
        self.menu_export_all_map.setText(_translate("MainWindow", "导出所有Erlang地图配置"))
        self.menu_export_all_c_map.setText(_translate("MainWindow", "导出所有C地图配置"))

