
SRC_DIRS := d:/Job/p18/p18_svr_code/src/work_helper/*.erl \
			d:/Job/p18/p18_svr_code/src/util/*.erl \
			d:/Job/p18/p18_svr_code/src/tools/*.erl \
			d:/Job/p18/p18_svr_code/src/test/*.erl \
			d:/Job/p18/p18_svr_code/src/server/scene_ctr/*.erl \
			d:/Job/p18/p18_svr_code/src/server/db/update_mnesia/*.erl \
			d:/Job/p18/p18_svr_code/src/server/db/*.erl \
			d:/Job/p18/p18_svr_code/src/server/cross/*.erl \
			d:/Job/p18/p18_svr_code/src/server/agent_ctr/*.erl \
			d:/Job/p18/p18_svr_code/src/rank/*.erl \
			d:/Job/p18/p18_svr_code/src/pt/*.erl \
			d:/Job/p18/p18_svr_code/src/network/*.erl \
			d:/Job/p18/p18_svr_code/src/logger/*.erl \
			d:/Job/p18/p18_svr_code/src/lib/recon/*.erl \
			d:/Job/p18/p18_svr_code/src/lib/my_lib/*.erl \
			d:/Job/p18/p18_svr_code/src/lib/json/*.erl \
			d:/Job/p18/p18_svr_code/src/lib/*.erl \
			d:/Job/p18/p18_svr_code/src/*.erl \
			d:/Job/p18/p18_svr_code/src/fun/task/*.erl \
			d:/Job/p18/p18_svr_code/src/fun/server/gm/*.erl \
			d:/Job/p18/p18_svr_code/src/fun/server/*.erl \
			d:/Job/p18/p18_svr_code/src/fun/sdk/*.erl \
			d:/Job/p18/p18_svr_code/src/fun/scene_sort/*.erl \
			d:/Job/p18/p18_svr_code/src/fun/program_config/*.erl \
			d:/Job/p18/p18_svr_code/src/fun/dataCountService/*.erl \
			d:/Job/p18/p18_svr_code/src/fun/count/*.erl \
			d:/Job/p18/p18_svr_code/src/fun/ai/*.erl \
			d:/Job/p18/p18_svr_code/src/config/Scene_script/scene_on_time/*.erl \
			d:/Job/p18/p18_svr_code/src/config/Scene_script/scene_item/*.erl \
			d:/Job/p18/p18_svr_code/src/config/Scene_script/scene_config/*.erl \
			d:/Job/p18/p18_svr_code/src/config/Scene_script/monster_on_time/*.erl \
			d:/Job/p18/p18_svr_code/src/config/data/*.erl \
			d:/Job/p18/p18_svr_code/src/config/battle/*.erl \
			d:/Job/p18/p18_svr_code/src/common/*.erl \
			
include ./include.mk

$(EBIN_DIR)/%.$(EMULATOR): $(hrl) d:/Job/p18/p18_svr_code/src/work_helper/%.erl 
	$(ERLC) $(ERLC_FLAGS) -o $(EBIN_DIR) $<
$(EBIN_DIR)/%.$(EMULATOR): $(hrl) d:/Job/p18/p18_svr_code/src/util/%.erl 
	$(ERLC) $(ERLC_FLAGS) -o $(EBIN_DIR) $<
$(EBIN_DIR)/%.$(EMULATOR): $(hrl) d:/Job/p18/p18_svr_code/src/tools/%.erl 
	$(ERLC) $(ERLC_FLAGS) -o $(EBIN_DIR) $<
$(EBIN_DIR)/%.$(EMULATOR): $(hrl) d:/Job/p18/p18_svr_code/src/test/%.erl 
	$(ERLC) $(ERLC_FLAGS) -o $(EBIN_DIR) $<
$(EBIN_DIR)/%.$(EMULATOR): $(hrl) d:/Job/p18/p18_svr_code/src/server/scene_ctr/%.erl 
	$(ERLC) $(ERLC_FLAGS) -o $(EBIN_DIR) $<
$(EBIN_DIR)/%.$(EMULATOR): $(hrl) d:/Job/p18/p18_svr_code/src/server/db/update_mnesia/%.erl 
	$(ERLC) $(ERLC_FLAGS) -o $(EBIN_DIR) $<
$(EBIN_DIR)/%.$(EMULATOR): $(hrl) d:/Job/p18/p18_svr_code/src/server/db/%.erl 
	$(ERLC) $(ERLC_FLAGS) -o $(EBIN_DIR) $<
$(EBIN_DIR)/%.$(EMULATOR): $(hrl) d:/Job/p18/p18_svr_code/src/server/cross/%.erl 
	$(ERLC) $(ERLC_FLAGS) -o $(EBIN_DIR) $<
$(EBIN_DIR)/%.$(EMULATOR): $(hrl) d:/Job/p18/p18_svr_code/src/server/agent_ctr/%.erl 
	$(ERLC) $(ERLC_FLAGS) -o $(EBIN_DIR) $<
$(EBIN_DIR)/%.$(EMULATOR): $(hrl) d:/Job/p18/p18_svr_code/src/rank/%.erl 
	$(ERLC) $(ERLC_FLAGS) -o $(EBIN_DIR) $<
$(EBIN_DIR)/%.$(EMULATOR): $(hrl) d:/Job/p18/p18_svr_code/src/pt/%.erl 
	$(ERLC) $(ERLC_FLAGS) -o $(EBIN_DIR) $<
$(EBIN_DIR)/%.$(EMULATOR): $(hrl) d:/Job/p18/p18_svr_code/src/network/%.erl 
	$(ERLC) $(ERLC_FLAGS) -o $(EBIN_DIR) $<
$(EBIN_DIR)/%.$(EMULATOR): $(hrl) d:/Job/p18/p18_svr_code/src/logger/%.erl 
	$(ERLC) $(ERLC_FLAGS) -o $(EBIN_DIR) $<
$(EBIN_DIR)/%.$(EMULATOR): $(hrl) d:/Job/p18/p18_svr_code/src/lib/recon/%.erl 
	$(ERLC) $(ERLC_FLAGS) -o $(EBIN_DIR) $<
$(EBIN_DIR)/%.$(EMULATOR): $(hrl) d:/Job/p18/p18_svr_code/src/lib/my_lib/%.erl 
	$(ERLC) $(ERLC_FLAGS) -o $(EBIN_DIR) $<
$(EBIN_DIR)/%.$(EMULATOR): $(hrl) d:/Job/p18/p18_svr_code/src/lib/json/%.erl 
	$(ERLC) $(ERLC_FLAGS) -o $(EBIN_DIR) $<
$(EBIN_DIR)/%.$(EMULATOR): $(hrl) d:/Job/p18/p18_svr_code/src/lib/%.erl 
	$(ERLC) $(ERLC_FLAGS) -o $(EBIN_DIR) $<
$(EBIN_DIR)/%.$(EMULATOR): $(hrl) d:/Job/p18/p18_svr_code/src/%.erl 
	$(ERLC) $(ERLC_FLAGS) -o $(EBIN_DIR) $<
$(EBIN_DIR)/%.$(EMULATOR): $(hrl) d:/Job/p18/p18_svr_code/src/fun/task/%.erl 
	$(ERLC) $(ERLC_FLAGS) -o $(EBIN_DIR) $<
$(EBIN_DIR)/%.$(EMULATOR): $(hrl) d:/Job/p18/p18_svr_code/src/fun/server/gm/%.erl 
	$(ERLC) $(ERLC_FLAGS) -o $(EBIN_DIR) $<
$(EBIN_DIR)/%.$(EMULATOR): $(hrl) d:/Job/p18/p18_svr_code/src/fun/server/%.erl 
	$(ERLC) $(ERLC_FLAGS) -o $(EBIN_DIR) $<
$(EBIN_DIR)/%.$(EMULATOR): $(hrl) d:/Job/p18/p18_svr_code/src/fun/sdk/%.erl 
	$(ERLC) $(ERLC_FLAGS) -o $(EBIN_DIR) $<
$(EBIN_DIR)/%.$(EMULATOR): $(hrl) d:/Job/p18/p18_svr_code/src/fun/scene_sort/%.erl 
	$(ERLC) $(ERLC_FLAGS) -o $(EBIN_DIR) $<
$(EBIN_DIR)/%.$(EMULATOR): $(hrl) d:/Job/p18/p18_svr_code/src/fun/program_config/%.erl 
	$(ERLC) $(ERLC_FLAGS) -o $(EBIN_DIR) $<
$(EBIN_DIR)/%.$(EMULATOR): $(hrl) d:/Job/p18/p18_svr_code/src/fun/dataCountService/%.erl 
	$(ERLC) $(ERLC_FLAGS) -o $(EBIN_DIR) $<
$(EBIN_DIR)/%.$(EMULATOR): $(hrl) d:/Job/p18/p18_svr_code/src/fun/count/%.erl 
	$(ERLC) $(ERLC_FLAGS) -o $(EBIN_DIR) $<
$(EBIN_DIR)/%.$(EMULATOR): $(hrl) d:/Job/p18/p18_svr_code/src/fun/ai/%.erl 
	$(ERLC) $(ERLC_FLAGS) -o $(EBIN_DIR) $<
$(EBIN_DIR)/%.$(EMULATOR): $(hrl) d:/Job/p18/p18_svr_code/src/config/Scene_script/scene_on_time/%.erl 
	$(ERLC) $(ERLC_FLAGS) -o $(EBIN_DIR) $<
$(EBIN_DIR)/%.$(EMULATOR): $(hrl) d:/Job/p18/p18_svr_code/src/config/Scene_script/scene_item/%.erl 
	$(ERLC) $(ERLC_FLAGS) -o $(EBIN_DIR) $<
$(EBIN_DIR)/%.$(EMULATOR): $(hrl) d:/Job/p18/p18_svr_code/src/config/Scene_script/scene_config/%.erl 
	$(ERLC) $(ERLC_FLAGS) -o $(EBIN_DIR) $<
$(EBIN_DIR)/%.$(EMULATOR): $(hrl) d:/Job/p18/p18_svr_code/src/config/Scene_script/monster_on_time/%.erl 
	$(ERLC) $(ERLC_FLAGS) -o $(EBIN_DIR) $<
$(EBIN_DIR)/%.$(EMULATOR): $(hrl) d:/Job/p18/p18_svr_code/src/config/data/%.erl 
	$(ERLC) $(ERLC_FLAGS) -o $(EBIN_DIR) $<
$(EBIN_DIR)/%.$(EMULATOR): $(hrl) d:/Job/p18/p18_svr_code/src/config/battle/%.erl 
	$(ERLC) $(ERLC_FLAGS) -o $(EBIN_DIR) $<
$(EBIN_DIR)/%.$(EMULATOR): $(hrl) d:/Job/p18/p18_svr_code/src/common/%.erl 
	$(ERLC) $(ERLC_FLAGS) -o $(EBIN_DIR) $<
