# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tab_conf.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TabConfig(object):
    def setupUi(self, TabConfig):
        TabConfig.setObjectName("TabConfig")
        TabConfig.resize(1085, 602)
        self.verticalLayout = QtWidgets.QVBoxLayout(TabConfig)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(5)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.groupBox = QtWidgets.QGroupBox(TabConfig)
        self.groupBox.setTitle("")
        self.groupBox.setFlat(False)
        self.groupBox.setCheckable(False)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(self.groupBox)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(108, 117, 125))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(108, 117, 125))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label.setPalette(palette)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.m_edit_s_dir = QtWidgets.QLineEdit(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.m_edit_s_dir.sizePolicy().hasHeightForWidth())
        self.m_edit_s_dir.setSizePolicy(sizePolicy)
        self.m_edit_s_dir.setText("")
        self.m_edit_s_dir.setFrame(False)
        self.m_edit_s_dir.setReadOnly(True)
        self.m_edit_s_dir.setClearButtonEnabled(False)
        self.m_edit_s_dir.setObjectName("m_edit_s_dir")
        self.horizontalLayout_3.addWidget(self.m_edit_s_dir)
        self.m_btn_s_dir = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.m_btn_s_dir.sizePolicy().hasHeightForWidth())
        self.m_btn_s_dir.setSizePolicy(sizePolicy)
        self.m_btn_s_dir.setMinimumSize(QtCore.QSize(0, 30))
        self.m_btn_s_dir.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.m_btn_s_dir.setFont(font)
        self.m_btn_s_dir.setAutoFillBackground(False)
        self.m_btn_s_dir.setStyleSheet("background-color: rgb(45, 135, 225);\n"
"color: rgb(255, 255, 255);")
        self.m_btn_s_dir.setFlat(False)
        self.m_btn_s_dir.setObjectName("m_btn_s_dir")
        self.horizontalLayout_3.addWidget(self.m_btn_s_dir)
        self.horizontalLayout_3.setStretch(1, 1)
        self.horizontalLayout_2.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(TabConfig)
        self.groupBox_2.setTitle("")
        self.groupBox_2.setFlat(False)
        self.groupBox_2.setCheckable(False)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(108, 117, 125))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(108, 117, 125))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_2.setPalette(palette)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_4.addWidget(self.label_2)
        self.m_edit_c_dir = QtWidgets.QLineEdit(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.m_edit_c_dir.sizePolicy().hasHeightForWidth())
        self.m_edit_c_dir.setSizePolicy(sizePolicy)
        self.m_edit_c_dir.setFrame(False)
        self.m_edit_c_dir.setReadOnly(True)
        self.m_edit_c_dir.setObjectName("m_edit_c_dir")
        self.horizontalLayout_4.addWidget(self.m_edit_c_dir)
        self.m_btn_c_dir = QtWidgets.QPushButton(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.m_btn_c_dir.sizePolicy().hasHeightForWidth())
        self.m_btn_c_dir.setSizePolicy(sizePolicy)
        self.m_btn_c_dir.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(45, 135, 225);")
        self.m_btn_c_dir.setObjectName("m_btn_c_dir")
        self.horizontalLayout_4.addWidget(self.m_btn_c_dir)
        self.horizontalLayout_4.setStretch(1, 1)
        self.horizontalLayout_2.addWidget(self.groupBox_2)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setSpacing(10)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.m_search = QtWidgets.QLineEdit(TabConfig)
        self.m_search.setMinimumSize(QtCore.QSize(0, 30))
        self.m_search.setObjectName("m_search")
        self.horizontalLayout_5.addWidget(self.m_search)
        self.m_btn_all_s = QtWidgets.QPushButton(TabConfig)
        self.m_btn_all_s.setMinimumSize(QtCore.QSize(0, 30))
        self.m_btn_all_s.setStyleSheet("background-color: rgb(45, 135, 225);\n"
"color: rgb(255, 255, 255);")
        self.m_btn_all_s.setObjectName("m_btn_all_s")
        self.horizontalLayout_5.addWidget(self.m_btn_all_s)
        self.m_btn_all_c = QtWidgets.QPushButton(TabConfig)
        self.m_btn_all_c.setMinimumSize(QtCore.QSize(0, 30))
        self.m_btn_all_c.setStyleSheet("background-color: rgb(45, 135, 225);\n"
"color: rgb(255, 255, 255);")
        self.m_btn_all_c.setObjectName("m_btn_all_c")
        self.horizontalLayout_5.addWidget(self.m_btn_all_c)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.m_table = QtWidgets.QTableWidget(TabConfig)
        self.m_table.setAlternatingRowColors(True)
        self.m_table.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.m_table.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.m_table.setColumnCount(0)
        self.m_table.setObjectName("m_table")
        self.m_table.setRowCount(0)
        self.m_table.verticalHeader().setSortIndicatorShown(True)
        self.verticalLayout.addWidget(self.m_table)
        self.verticalLayout.setStretch(2, 1)

        self.retranslateUi(TabConfig)
        QtCore.QMetaObject.connectSlotsByName(TabConfig)

    def retranslateUi(self, TabConfig):
        _translate = QtCore.QCoreApplication.translate
        TabConfig.setWindowTitle(_translate("TabConfig", "Form"))
        self.label.setText(_translate("TabConfig", "后端导出目录："))
        self.m_btn_s_dir.setText(_translate("TabConfig", "设置"))
        self.label_2.setText(_translate("TabConfig", "前端导出目录："))
        self.m_btn_c_dir.setText(_translate("TabConfig", "设置"))
        self.m_search.setPlaceholderText(_translate("TabConfig", "模糊匹配搜索"))
        self.m_btn_all_s.setText(_translate("TabConfig", "导出所有后端配置"))
        self.m_btn_all_c.setText(_translate("TabConfig", "导出所有前端配置"))
        self.m_table.setSortingEnabled(True)
