# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tab_lang.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Lang(object):
    def setupUi(self, Lang):
        Lang.setObjectName("Lang")
        Lang.resize(747, 601)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(Lang.sizePolicy().hasHeightForWidth())
        Lang.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        Lang.setFont(font)
        self.verticalLayout = QtWidgets.QVBoxLayout(Lang)
        self.verticalLayout.setObjectName("verticalLayout")
        self.m_tab_lang = QtWidgets.QTableWidget(Lang)
        self.m_tab_lang.setAlternatingRowColors(True)
        self.m_tab_lang.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.m_tab_lang.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.m_tab_lang.setColumnCount(0)
        self.m_tab_lang.setObjectName("m_tab_lang")
        self.m_tab_lang.setRowCount(0)
        self.m_tab_lang.verticalHeader().setSortIndicatorShown(True)
        self.verticalLayout.addWidget(self.m_tab_lang)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.m_btn_all = QtWidgets.QPushButton(Lang)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.m_btn_all.sizePolicy().hasHeightForWidth())
        self.m_btn_all.setSizePolicy(sizePolicy)
        self.m_btn_all.setMinimumSize(QtCore.QSize(0, 30))
        self.m_btn_all.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.m_btn_all.setFont(font)
        self.m_btn_all.setAutoFillBackground(False)
        self.m_btn_all.setStyleSheet("background-color: rgb(45, 135, 225);\n"
"color: rgb(255, 255, 255);")
        self.m_btn_all.setFlat(False)
        self.m_btn_all.setObjectName("m_btn_all")
        self.horizontalLayout.addWidget(self.m_btn_all)
        self.groupBox = QtWidgets.QGroupBox(Lang)
        self.groupBox.setTitle("")
        self.groupBox.setFlat(False)
        self.groupBox.setCheckable(False)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(self.groupBox)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(108, 117, 125))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(108, 117, 125))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label.setPalette(palette)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.m_edit_file = QtWidgets.QLineEdit(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.m_edit_file.sizePolicy().hasHeightForWidth())
        self.m_edit_file.setSizePolicy(sizePolicy)
        self.m_edit_file.setText("")
        self.m_edit_file.setFrame(False)
        self.m_edit_file.setReadOnly(True)
        self.m_edit_file.setClearButtonEnabled(False)
        self.m_edit_file.setObjectName("m_edit_file")
        self.horizontalLayout_3.addWidget(self.m_edit_file)
        self.m_btn_file = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.m_btn_file.sizePolicy().hasHeightForWidth())
        self.m_btn_file.setSizePolicy(sizePolicy)
        self.m_btn_file.setMinimumSize(QtCore.QSize(0, 30))
        self.m_btn_file.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.m_btn_file.setFont(font)
        self.m_btn_file.setAutoFillBackground(False)
        self.m_btn_file.setStyleSheet("background-color: rgb(45, 135, 225);\n"
"color: rgb(255, 255, 255);")
        self.m_btn_file.setFlat(False)
        self.m_btn_file.setObjectName("m_btn_file")
        self.horizontalLayout_3.addWidget(self.m_btn_file)
        self.horizontalLayout_3.setStretch(1, 1)
        self.horizontalLayout.addWidget(self.groupBox)
        self.m_btn_incr = QtWidgets.QPushButton(Lang)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.m_btn_incr.sizePolicy().hasHeightForWidth())
        self.m_btn_incr.setSizePolicy(sizePolicy)
        self.m_btn_incr.setMinimumSize(QtCore.QSize(0, 30))
        self.m_btn_incr.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.m_btn_incr.setFont(font)
        self.m_btn_incr.setAutoFillBackground(False)
        self.m_btn_incr.setStyleSheet("background-color: rgb(45, 135, 225);\n"
"color: rgb(255, 255, 255);")
        self.m_btn_incr.setFlat(False)
        self.m_btn_incr.setObjectName("m_btn_incr")
        self.horizontalLayout.addWidget(self.m_btn_incr)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.m_tab_export = QtWidgets.QTableWidget(Lang)
        self.m_tab_export.setAlternatingRowColors(True)
        self.m_tab_export.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.m_tab_export.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.m_tab_export.setColumnCount(0)
        self.m_tab_export.setObjectName("m_tab_export")
        self.m_tab_export.setRowCount(0)
        self.m_tab_export.verticalHeader().setSortIndicatorShown(True)
        self.verticalLayout.addWidget(self.m_tab_export)
        self.verticalLayout.setStretch(0, 2)

        self.retranslateUi(Lang)
        QtCore.QMetaObject.connectSlotsByName(Lang)

    def retranslateUi(self, Lang):
        _translate = QtCore.QCoreApplication.translate
        Lang.setWindowTitle(_translate("Lang", "Form"))
        self.m_tab_lang.setSortingEnabled(True)
        self.m_btn_all.setText(_translate("Lang", "提取全部中文"))
        self.label.setText(_translate("Lang", "对比文件："))
        self.m_btn_file.setText(_translate("Lang", "选择对比文件"))
        self.m_btn_incr.setText(_translate("Lang", "提取增量中文"))
        self.m_tab_export.setSortingEnabled(True)
